name: Commit sites to storybook-pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow commit and push

permissions: write-all

jobs:
  # upload sites folder as artifact
  upload-sites:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: ls -la

      - name: Save folder as artifact
        uses: actions/upload-artifact@v2
        with:
          name: site-folder
          path: ./sites

  get-aritifact:
    runs-on: ubuntu-latest
    needs: upload-sites
    steps:
      - run: echo ${{ github.repository }}
      # log github workspace
      - run: echo ${{ github.workspace }}

      - name: Checkout repo storybook-pages
        uses: actions/checkout@v3
        with:
          repository: yzhou-willow/storybook-pages
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: site-folder
          path: ./sites
      - run: ls -la

      - name: Commit changes to storybook-pages with github authorization
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Update site folder"
          git push
